"""Add OTP table retry

Revision ID: 80811ffc5ca6
Revises: b59c4a5bf2b1
Create Date: 2025-11-28 19:58:47.668855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80811ffc5ca6'
down_revision = 'b59c4a5bf2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otp')
    # ### end Alembic commands ###
